version: "3.8"

services:

  #Nginx Server
  server:
    container_name: 'nginx_server'
    image: 'nginx:alpine'
    ports:
      - '8000:80' # port server
      - '3333:81' # port front end
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
      - ./frontend/dist/:/usr/share/nginx/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #PHP Service
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    container_name: 'backend-test'
    restart: unless-stopped
    volumes:
     - ./backend:/var/www/html
     - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #MySQL Service
  mysql:
    image: mysql:8.0
    container_name: test_db
    restart: unless-stopped
    ports:
      - "3309:3306"
    volumes:
      # - ./docker/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=todolist
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
